---
# role: jomrr.baseline
# file: tasks/main.yml

- name: "Import tasks for gather_facts"
  ansible.builtin.include_tasks: gather_facts.yml
  loop: "{{ baseline_cmd | dict2items }}"
  loop_control:
    loop_var: baseline_pkg_mgr

- name: "Bootstrap with python3"
  become: false
  ansible.builtin.raw: "{{ baseline_cmd[baseline_package_manager] }} {{ baseline_pkg3[baseline_package_manager] }}"
  check_mode: false
  changed_when: false
  ignore_errors: true
  register: bootstrap_install_result

- name: "Bootstrap with python2"
  become: false
  ansible.builtin.raw: "{{ baseline_cmd[baseline_package_manager] }} {{ baseline_pkg2[baseline_package_manager] }}"
  check_mode: false
  changed_when: false
  when: bootstrap_install_result is failed
