---
# role: jomrr.baseline
# file: molecule/default/molecule.yml

dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: almalinux-baseline
    image: "jomrr/molecule-almalinux:latest"
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
  - name: alpine-baseline
    image: "jomrr/molecule-alpine:latest"
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
  - name: amazonlinux-baseline
    image: "jomrr/molecule-amazonlinux:latest"
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: arch-baseline
    image: "jomrr/molecule-archlinux:latest"
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: centos-baseline
    image: "jomrr/molecule-centos:latest"
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: debian-baseline
    image: "jomrr/molecule-debian:latest"
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: fedora-baseline
    image: "jomrr/molecule-fedora:latest"
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: opensuse-baseline
    image: "jomrr/molecule-opensuse:15"
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: tumbleweed-baseline
    image: "jomrr/molecule-opensuse:tumbleweed"
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: oraclelinux-baseline
    image: "jomrr/molecule-oraclelinux:latest"
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: ubuntu-baseline
    image: "jomrr/molecule-ubuntu:latest"
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
provisioner:
  name: ansible
  log: true
  playbooks:
    converge: ../resources/playbooks/converge.yml
    verify: ../resources/playbooks/verify.yml
  inventory:
    group_vars:
      all:
        baseline_role_enabled: true
scenario:
  create_sequence:
    - dependency
    - create
    - prepare
  converge_sequence:
    - converge
  destroy_sequence:
    - cleanup
    - destroy
  test_sequence:
    - converge
    - idempotence
    - verify
verifier:
  name: ansible
