---
# role: ansible-role-baseline
# file: molecule/tox/molecule.yml

dependency:
  name: galaxy
  options:
    requirements-file: molecule/tox/requirements.yml
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: baseline-${TOX_ENVNAME:-"default"}
    image: "${uns:-jam82}/molecule-${img:-debian}:${tag:-latest}"
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
provisioner:
  name: ansible
  log: true
  playbooks:
    converge: ../resources/playbooks/converge.yml
    verify: ../resources/playbooks/verify.yml
verifier:
  name: ansible
